// Claude Grid Workshop adapter for vendor/santalla-screw-label/Pred_GridfinityLabel.scad
// (Nadia Santalla, GPL-3.0-or-later). Changes, nothing else:
//  - BOSL includes point at the bundled library instead of /usr/share/openscad/...
//  - Customizer groups and dropdowns for the icon settings
//  - default font is one the browser engine ships (Helvetica isn't available)

/*
 Originally authored by Nadia Santalla <nadia@santalla.io>
 Licensed under GNU General Public License v3.0 or later
 https://www.gnu.org/licenses/gpl-3.0-standalone.html
 */

/*
 Printing tips:
 - Print one and measure the label height, which should be exactly 12mm. If it isn't, and adjust elephant foot compensation accordingly on your slicer, otherwise the label won't fit on the bin as the tolerance is tight.
 - Enable slower speed for small perimeters setting on your slicer, and set a very slow speed (~20mm/s). This helps with icon detail, e.g. preventing the hex from looking like a circle.
 - Thin layers (.12mm) work better for detail, and allows the base to be 2 layers thick, which helps to hide porosity and small gaps.
 */

// # User parameters.

/* [Screw] */
// Drive on the head: internal (hex, slot, phillips...) or an external hex/square head
iconType = "internal"; // [internal, external]

// Available types for internal screws:
// - hex, slot, phillips, torx, square, triangle, tripoint.
// Available types for internal screws:
// - hex
iconKey = "torx"; // [hex, slot, phillips, torx, square, triangle, tripoint]

// Head shape
iconHead = "socket"; // [socket, button, flat]

// Screw length in mm (the drawing is capped at 24)
screwLen = 50;

/* [Text] */
// Thread size shown on the label
screwText = "M3";

pointy = false; // Useful for wood screws.

// Pick one that's present on your system.
font="Liberation Sans:style=Bold"; // [Liberation Sans:style=Bold, Liberation Sans, Liberation Mono:style=Bold, Liberation Mono]

/* [Hidden] */
// Autogenerated from screwLen, but can be customized.
labelText = str(screwText, "×", screwLen);

// # Internal parameters

$fn = 32;

labelY = 12;
labelX = 35.8;

flapY = 6.7;
flapX = 1;

border = 0.8;

fillet = 1;

baseZ = 0.4;
totalZ = 0.8;

fontSize = 4;
iconSize = 5;

headWidth = 3;
headHeight = iconSize;
bodyHeight = iconSize/2;

topZ = totalZ - baseZ;

include <BOSL/shapes.scad>
include <BOSL/constants.scad>
include <BOSL/transforms.scad>

union() {
    base();
    up(topZ) border();
    up(topZ) label();
}

module label() {
    borderSpacing = .33;
    topOffset = labelY/2 - border - borderSpacing - iconSize/2;
    botOffset = labelY/2 - border - borderSpacing - fontSize/2;

    back(topOffset) labelGraphic(
        l=screwLen,
        head=iconHead,
        key=iconKey,
        type=iconType,
        pointy=pointy
    );

    fwd(botOffset) labelText(labelText, font);
}

module labelText(t="", font="") {
    linear_extrude(topZ) 
    text(
        t,
        font=font,
        size=fontSize, halign="center", valign="center"
    );
}

module labelGraphic(l, head="", key="", type="", pointy=false) {
    screwLen = min(l, 24);
    truncated = l > screwLen;

    separation = 1;
    leftExtra = headWidth + iconSize + separation;
    right(leftExtra/2) union() {
        labelScrewBody(screwLen, pointy, truncated);
        left(screwLen/2) labelScrewHead(head);
        left(screwLen/2 + headWidth + iconSize/2 + separation)
            labelIcon(key, type);
    }
}

module labelIcon(key="", type="") {
    if (type == "internal") {
        indentLen = iconSize * .75;
        difference() {
            cyl(h=topZ, d=iconSize, align=V_TOP);
            if (key == "hex") {
                cyl(h=topZ+.1, d=indentLen, align=V_TOP, $fn=6);
            };
            if (key == "slot") {
                cuboid([iconSize, iconSize/6, topZ+.1], align=V_TOP);
            };
            if (key == "phillips") {
                cuboid([indentLen, 1, topZ+.1], align=V_TOP);
                rot(90) cuboid([indentLen, 1, topZ+.1], align=V_TOP);
                rot(45) cuboid([1.8, 1.8, topZ+.1], align=V_TOP);
            };
            if (key == "torx") {
                difference() {
                    // .7 here is a magic constant that made this slice good. YMMV.
                    cyl(h=topZ+.1, d=indentLen, align=V_TOP);
                    zring(n=6, r=indentLen*.7)
                        cyl(h=topZ+.2, d=indentLen*.7, align=V_TOP);
                };
            };
            if (key == "square") {
                rot(45) cyl(h=topZ+.1, d=indentLen, align=V_TOP, $fn=4);
            };
            if (key == "triangle") {
                rot(-30) cyl(h=topZ+.1, d=indentLen, align=V_TOP, $fn=3);
            };
            if (key == "tripoint") {
                rot(-30) zring(n=3, r=indentLen/4) cuboid(
                    [indentLen/2, indentLen/4, topZ+.2],
                    align=V_TOP
                );
            };
        }
    }
    if (type == "external") {
        if (key == "hex") {
            cyl(h=topZ, d=iconSize, align=V_TOP, $fn=6);
        };
        if (key == "square") {
            rot(45) cyl(h=topZ, d=iconSize, align=V_TOP, $fn=4);
        };
    }
}

module labelScrewHead(head="") {
    if (head == "socket") {
        left(headWidth/2) cuboid(
            [headWidth, headHeight, topZ],
            align=V_TOP,
            edges=EDGES_Z_LF,
            fillet=.3
        );
    }
    if (head == "button") {
        difference() {
            cyl(
                d=headHeight,
                h=topZ,
                align=V_TOP
            );
            right(headHeight/4) cuboid(
                [headHeight/2, headHeight, topZ+.1],
                align=V_TOP
            );
        }
    }
    if (head == "flat") {
        left(headWidth) right(headWidth) up(topZ/2) yrot(-90) prismoid(
            size1=[topZ, bodyHeight],
            size2=[topZ, headHeight],
            h=headWidth*2/3
        );
    }
}

module labelScrewBody(l, pointy=false, truncated=false) {
    difference() {
        cuboid(
            [l, bodyHeight, topZ],
            align=V_TOP,
            edges=EDGES_Z_RT,
            chamfer=pointy ? bodyHeight/2 : .5
        );
        if (truncated) {
            rot(-30) cuboid(
                [1, 100, topZ+1],
                align=V_TOP
            );
        }
    }
}

module border() {
    difference() {
        cuboid(
            [labelX, labelY, baseZ], 
            align=V_TOP, 
            edges=EDGES_Z_ALL,
            fillet=fillet
        );
        cuboid(
            [labelX-border*2, labelY-border*2, baseZ*2+1],
            edges=EDGES_Z_ALL,
            fillet=fillet/2
        );
    }

}

module base() {
    cuboid(
        [labelX, labelY, baseZ], 
        align=V_TOP, 
        edges=EDGES_Z_ALL, 
        fillet=fillet
    );
    cuboid(
        [labelX + flapX * 2, flapY, baseZ], 
        align=V_TOP,
        edges=EDGES_Z_ALL,
        chamfer=1
    );
}
